apiVersion: v1
kind: Secret
metadata:
  name: {{ include "insight-job.fullname" . }}-app-secrets
  labels:
    {{- include "insight-job.labels" . | nindent 4 }}
type: Opaque
stringData:
  BACKEND_PORT: {{ .Values.api.env.backendPort | quote }}
  JWT_SECRET: {{ .Values.api.env.jwtSecret | quote }}
  FRONTEND_ORIGIN: {{ .Values.api.env.frontendOrigin | quote }}
  COOKIE_SECURE: {{ .Values.api.env.cookieSecure | quote }}
  SMTP_HOST: {{ .Values.api.env.smtpHost | quote }}
  SMTP_PORT: {{ .Values.api.env.smtpPort | quote }}
  SMTP_SECURE: {{ .Values.api.env.smtpSecure | quote }}
  SMTP_USER: {{ .Values.api.env.smtpUser | quote }}
  SMTP_PASS: {{ .Values.api.env.smtpPass | quote }}
  EMAIL_FROM_EMAIL: {{ .Values.api.env.emailFromEmail | quote }}
  EMAIL_FROM_NAME: {{ .Values.api.env.emailFromName | quote }}
  POSTGRES_HOST: {{ printf "%s-postgres" (include "insight-job.fullname" .) | quote }}
  POSTGRES_PORT: {{ .Values.postgres.service.port | quote }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
